

version: '3.7'

services:
  evaluacion_api:
    build:
      context: ./evaluacion
      dockerfile: Dockerfile

    volumes:
      - ./evaluacion:/code
    env_file:
      - ./evaluacion/.env
    networks:
      - evaluacion_network

  api_gateway:
    image: nginx:1.27
    restart: always

    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - evaluacion_api
    networks:
      - evaluacion_network


networks:
  evaluacion_network:
    driver: bridge