# Generated by Django 5.1.7 on 2025-03-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cnel",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("codigoCuentaAnterior", models.CharField(max_length=255)),
                ("codigoCuentaNuevo", models.CharField(max_length=255)),
                ("cuenAnterior", models.CharField(max_length=255)),
                ("cuenNuevo", models.CharField(max_length=255)),
                ("cuentaContrato", models.CharField(max_length=255)),
                ("cedulaRuc", models.CharField(max_length=255)),
                ("idUnAnterior", models.CharField(max_length=255)),
                ("idUnNueva", models.CharField(max_length=255)),
                ("fechaRegistro", models.DateTimeField()),
                ("unidadNegocio", models.CharField(max_length=255)),
                ("codUnidadNegocio", models.CharField(max_length=255)),
                ("siglasUnidadNegocio", models.CharField(max_length=255)),
                ("interesCondonadoJson", models.CharField(max_length=255)),
                ("mensajeCondonacion", models.CharField(max_length=255)),
                ("correoRegistrado", models.CharField(max_length=255)),
                ("deuda", models.FloatField()),
                ("fechaVencimiento", models.DateTimeField()),
                ("planillasVencidas", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("identifier", models.CharField(max_length=100)),
            ],
        ),
    ]
