# Generated by Django 5.1.7 on 2025-03-08 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Field",
                "verbose_name_plural": "Fields",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProfileType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Profile Type",
                "verbose_name_plural": "Profile Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Prospect",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("agent", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "cedula",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("nombres", models.CharField(max_length=255)),
                ("apellidos", models.CharField(max_length=255)),
                ("ciudadania", models.CharField(max_length=255)),
                ("fechaNacimiento", models.DateField()),
                ("estadoCivil", models.CharField(max_length=255)),
                ("profesion", models.CharField(max_length=255)),
                ("nivelEstudios", models.CharField(max_length=255)),
                ("esCliente", models.BooleanField()),
                ("tipoPersona", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProfileTypeField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.field"
                    ),
                ),
                (
                    "profile_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.profiletype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile Type Field",
                "verbose_name_plural": "Profile Type Fields",
                "ordering": ["profile_type"],
            },
        ),
        migrations.AddField(
            model_name="profiletype",
            name="fields",
            field=models.ManyToManyField(
                through="core.ProfileTypeField", to="core.field"
            ),
        ),
        migrations.CreateModel(
            name="ScoreHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("agent", models.CharField(blank=True, max_length=255, null=True)),
                ("score", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_history",
                        to="core.prospect",
                    ),
                ),
            ],
            options={
                "db_table": "score_history",
            },
        ),
        migrations.AddField(
            model_name="prospect",
            name="score",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prospect",
                to="core.scorehistory",
            ),
        ),
    ]
