# Generated by Django 5.1.7 on 2025-03-09 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='prospect',
            name='score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.scorehistory'),
        ),
    ]
