# Generated by Django 5.1.7 on 2025-03-09 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_prospect_agent_remove_prospect_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_solicitado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plazo', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(default='En revisión', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_applications', to='core.prospect')),
            ],
        ),
    ]
