# Generated by Django 5.1.7 on 2025-03-09 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_creditapplication'),
    ]

    operations = [
    ]
